### ISSUE TITLE
Can't start pysimcoder (Windows)

### ISSUE THREAD

**Issue by Herolars** [robertobucher/pysimCoder#106]
Hello,

I'm trying to install pysimCoder for windows with wsl and your guide, but i always get stuck with this error code when trying to start:

Traceback (most recent call last):
  File "/home/larse/pysimCoder/BlockEditor/pysimCoder.py", line 8, in <module>
    from supsisim.library import Library
  File "/home/larse/pysimCoder/toolbox/supsisim/supsisim/library.py", line 9, in <module>
    from supsisim.pyEdit import NewEditorMainWindow
  File "/home/larse/pysimCoder/toolbox/supsisim/supsisim/pyEdit.py", line 11, in <module>
    from supsisim.scene import Scene, GraphicsView
  File "/home/larse/pysimCoder/toolbox/supsisim/supsisim/scene.py", line 10, in <module>
    from .shv import ShvClient
  File "/home/larse/pysimCoder/toolbox/supsisim/supsisim/shv/__init__.py", line 3, in <module>
    from .client import ShvClient
  File "/home/larse/pysimCoder/toolbox/supsisim/supsisim/shv/client.py", line 8, in <module>
    from shv import RpcUrl, SimpleClient, RpcError, SHVType
ImportError: cannot import name 'SimpleClient' from 'shv' (/home/larse/.local/lib/python3.12/site-packages/shv/__init__.py).

Maybe you can help me  and find a solution

**Comment by michallenc** [comment]
Hi, the issue is probably in [pyshv](https://pypi.org/project/pyshv/) package versions, where in 0.8.0  `SimpleClient` was renamed to `SHVClient`. Could you install the older 0.7.3 version https://pypi.org/project/pyshv/0.7.3/ on your system? It should work fine with it.

I will send the merge request that updates the dependencies to work with 0.8.0 later today.

**Comment by Herolars** [comment]
Thanks i installed pyshv 0.7.3 and it worked!
